project '../prj/ViperSampleProject.xcodeproj'

platform :ios, '10.0'

inhibit_all_warnings!

target 'ViperSampleProject' do

  pod 'Typhoon'
  pod 'OCMock'
  pod 'RamblerTyphoonUtils'
  pod 'ViperMcFlurry'
  pod 'RamblerAppDelegateProxy'
  pod 'RamblerSegues'
  pod 'MagicalRecord'
  pod 'Nimbus/Models', :git => 'https://github.com/rambler-ios/nimbus'
  pod 'Nimbus/Collections', :git => 'https://github.com/rambler-ios/nimbus'
  pod 'AFNetworking'
  pod 'BGTableViewRowActionWithImage'
  
end
